### ISSUE TITLE
Settings for recommended policies are missing or not rendered

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#669]
Settings missing on recommended privileged pod policy.

[Screencast from 2024-03-26 13-55-40.webm](https://github.com/rancher/kubewarden-ui/assets/538604/bba5ee28-004f-4836-97f0-5984e7e3aac8)

Settings not rendered on privilege escalation policy.

[Screencast from 2024-03-26 13-59-53.webm](https://github.com/rancher/kubewarden-ui/assets/538604/66d9747e-649e-4fab-a85f-257f52a6cc01)

UI extension: 1.4.1
Rancher: 2.8.2

**Comment by aalves08** [comment]
@kravciak for the second item `Settings not rendered on privilege escalation policy`:

If it comes from the default policies, the problem lies with the fact that the UI elements only appear because they are interpreted from the `questions` part, hence why on creating CAP from the template `Allow Privilege Escalation PSP`, we get the `questions` part from the chart and the UI elements appear.

Now, during last friday's meeting, while editing a CAP created from the template `Allow Privilege Escalation PSP`, we got into this scenario where I wasn't expecting to get the UI elements, but turns out we have them because Jordon is fetching the questions part from ArtifactHub.

Now, the biggest question is why isn't this working for the default CAP's?

That's because we are missing the annotation for ArtifactHub...

**CAP from defaults**
![Screenshot 2024-04-15 at 15 50 26](https://github.com/rancher/kubewarden-ui/assets/97888974/96ac1bdf-ebaa-4f16-9027-0bb2d3d9cd77)

**CAP from template**
![Screenshot 2024-04-15 at 15 50 18](https://github.com/rancher/kubewarden-ui/assets/97888974/efb962f5-9018-4ea4-859d-838370b9c629)

Is it possible to include it on the default policies @viccuad @flavio ? does it need versioning of some sort?

If so, what adaptations are needed to current KW UI logic in order to get the version information correctly?

I think Jordon isn't taking that into account anywhere here: https://github.com/rancher/kubewarden-ui/blob/main/pkg/kubewarden/plugins/policy-class.js#L59-L77 🤔

**Comment by viccuad** [comment]
Yep, the questions.yaml are added as artifacthub pkg annotations, for artifacthub to return them via their API (we do that in the policies [here](https://github.com/kubewarden/allow-privilege-escalation-psp-policy/blob/main/artifacthub-pkg.yml#L43-L57)).

The questions-ui are tightly coupled with the policy binary (Wasm module);  each binary has a different ABI, and may accept different settings. Right now we are already making the assumption that the binary we push to the OCI registry, with a specific tag (e.g: `:v1.1.0`), matches that version. We could err here or suffer an attack. This is not a problem for policies under our control, could be for community policies from Artifacthub.

The ideal would be to include the questions into the [metadata](https://github.com/kubewarden/verify-image-signatures/blob/main/metadata.yml) that gets backed into the binary itself, and in the UI pull the binary from the OCI registry and read the questions that way. We will not do that for now.

> I think Jordon isn't taking that into account anywhere here: https://github.com/rancher/kubewarden-ui/blob/main/pkg/kubewarden/plugins/policy-class.js#L59-L77 🤔

That seems correct. From searching, it seemed to be added with https://github.com/rancher/kubewarden-ui/commit/5a3f6dd3e85a4504e5fcc089def84deba754bcc0.

On the Kubewarden policies side, for all, we don't add that `artifacthub/pkg` annotation. Neither the instantiated resources in cluster have that metadata.annotations. So I think it's added temporarily by the part of the UI that deals with creating the policy, and I think that's why we don't see it on the default policies.

Solutions that I can think of:
1. Add the metadata.annotations.`artifacthub/pkg` on the default policies template, on the kubewarden-defaults chart.
  Example, by doing this for all policies:
  https://github.com/kubewarden/helm-charts/compare/main...viccuad:helm-charts:add-artifacthubpkg-annot
  One can try by upgrading kubewarden-defaults from this repo, https://github.com/viccuad/helm-charts branch `add-artifacthubpkg-annot`. Afterwards, one can see the settings. 
2. Change the UI to always construct the artifacthub/pkg  name, to be able to query for questions for all artifacthub policies. Or maybe all those that are officially owned by Kubewarden. Hence the question settings will always be present for all policies regardless of how they were installed.
  
  
From those, I prefer number 2, as it is hacky but less hacky and more DRY than 1.
That is discounting that I am happy with current status quo  (if you want to change the policies, change the kubewarden-default values).

**Comment by viccuad** [comment]
At the end, de decided to go with an option 3, adding the questions for the default policies in the questions of the `kubewarden-defaults` chart. This is done here: https://github.com/kubewarden/helm-charts/pull/427

With this, the default policies are configurable via the chart. And the questions will always be matching the specific version of the policy (we take care of this manually for this default policies).

The UI should, for these default policies, to not allow changes via the "Edit Policy" ([this path](https://rancher.local/dashboard/c/local/kubewarden/policies.kubewarden.io.clusteradmissionpolicy/do-not-run-as-root?mode=edit#general)). Instead, when clicking on the "Edit Policy", it should show a page saying that the policy is owned by the `kubewarden-default` helm chart, and/or redirect there ([redirect to this path](https://rancher.local/dashboard/c/local/apps/charts/install?namespace=cattle-kubewarden-system&name=rancher-kubewarden-defaults&version=1.9.5-rc1&repo=vic-kubewarden-defaults&repo-type=cluster&chart=kubewarden-defaults#Recommended%20Policies))

For knowing if a policy is one of the default ones, the UI can check the policy labels: (maybe already does, given that it shows a banner for these)
```                                                                                                                                                                                                                                                         metadata.labels.app.kubernetes.io/managed-by: Helm
metadata.labels.app.kubernetes.io/part-of: kubewarden                                                                                                                                                                                                                                                                                  
```
